#与开发时版本相同的环境
FROM python:3.12

#设置工作目录
WORKDIR /app

#将当前目录内容复制到位于/app的容器中
COPY . /app
#安装指定包

RUN pip install --no-cache-dir -r requirements.txt

#使端口5000可供此容器外的环境使用
EXPOSE 5000

#在容器启动时，运行app.py
CMD ["flask", "run", "--host=0.0.0.0"]
